### ISSUE TITLE
can't install it in nixos

### ISSUE THREAD

**Issue by NestorLiao** [godamartonaron/GODA_pyPPG#19]
```
ia ❄️  impure (impurePythonEnv-env) on  main [✘!+?⇡] ZenSleep/ptt ❯   pip install pyPPG
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyPPG
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6b/bd/bd2baa51dd8714510894bb9d720c8dc6cba814df48882ad4c2ab990f910f/pyPPG-1.0.72-py3-none-any.whl (63 kB)
Collecting scipy==1.9.1 (from pyPPG)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz (42.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: /tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e
      Build dir: /tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e/.mesonpy-iy8mpebb/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.1
      C compiler for the host machine: gcc (gcc 13.2.0 "gcc (GCC) 13.2.0")
      C linker for the host machine: gcc ld.bfd 2.41
      C++ compiler for the host machine: g++ (gcc 13.2.0 "g++ (GCC) 13.2.0")
      C++ linker for the host machine: g++ ld.bfd 2.41
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 9.5.0 "GNU Fortran (GCC) 9.5.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.41
      Program cython found: YES (/tmp/pip-build-env-i4qda7fd/overlay/bin/cython)
      Program pythran found: YES (/tmp/pip-build-env-i4qda7fd/overlay/bin/pythran)
      Program cp found: YES (/nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/cp)
      Program python found: YES (/home/nestor/resin/ZenSleep/ptt/.venv/bin/python3.11)
      Found pkg-config: /nix/store/fyxva0kkcmaigwk4218l0zdy8z3s9sj3-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)

      ../../scipy/meson.build:40:0: ERROR: Command "/home/nestor/resin/ZenSleep/ptt/.venv/bin/python3.11 -c import os; os.chdir(".."); import numpy; print(numpy.get_include())" failed with status 1.

      A full log can be found at /tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e/.mesonpy-iy8mpebb/build/meson-logs/meson-log.txt
      + meson setup --native-file=/tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8 /tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e /tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e/.mesonpy-iy8mpebb/build
      Traceback (most recent call last):
        File "/home/nestor/resin/ZenSleep/ptt/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/nestor/resin/ZenSleep/ptt/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/nestor/resin/ZenSleep/ptt/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i4qda7fd/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8', '/tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e', '/tmp/pip-install-a_b2hsbk/scipy_3a0d65d42b014d02aee66ab42041068e/.mesonpy-iy8mpebb/build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

'''get nix environment below

{
  description = "A Nix-flake-based Python development environment";

  inputs.nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";

  outputs = {
    self,
    nixpkgs,
  }: let
    supportedSystems = ["x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"];
    forEachSupportedSystem = f:
      nixpkgs.lib.genAttrs supportedSystems (system:
        f {
          pkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = true;
            cudaSupport = true;
          };
        });
  in {
    devShells = forEachSupportedSystem ({pkgs}: {
      default = pkgs.mkShell {
        name = "impurePythonEnv";
        venvDir = "./.venv";

        buildInputs = with pkgs; [
          libsForQt5.qt5.qtwayland

          (with python3Packages; [
            python
            venvShellHook
            numpy
            pandas
            matplotlib
            scipy
            requests
            tkinter
          ])

          gfortran9

          pspp

          pkg-config
          taglib
          openssl
          git
          libxml2
          libxslt
          libzip
          zlib
        ];

        # Run this command, only after creating the virtual environment
        postVenvCreation = ''
          unset SOURCE_DATE_EPOCH
          # pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          # pip install -r requirements.txt
        '';

        # Now we can execute any commands within the virtual environment.
        # This is optional and can be left out to run pip manually.
        postShellHook = ''
          # allow pip to install wheels
          export QT_QPA_PLATFORM_PLUGIN_PATH="${pkgs.qt5.qtbase.bin}/lib/qt-${pkgs.qt5.qtbase.version}/plugins/platforms";
          export PYTHON_CONFIGURE_OPTS="--enable-shared"
          unset SOURCE_DATE_EPOCH
        '';
      };
    });
  };
}

'''

**Comment by NestorLiao** [comment]
set up a virtual mechine to run it, however when running the colab with the dataset provide in github meet such error:

test@pop-os:/run/user/1000/gvfs/smb-share:server=10.0.2.4,share=qemu/resin/ZenSleep/pyqt$ python3 ttest.py 
Traceback (most recent call last):
  File "/run/user/1000/gvfs/smb-share:server=10.0.2.4,share=qemu/resin/ZenSleep/pyqt/ttest.py", line 29, in <module>
    signal = load_data(data_path=data_path, start_sig=start_sig, end_sig=end_sig, use_tk=False)
  File "/home/test/.local/lib/python3.10/site-packages/pyPPG/datahandling.py", line 126, in load_data
    s.end_sig = len(sig)
UnboundLocalError: local variable 'sig' referenced before assignment

**Comment by godamartonaron** [comment]
https://pyppg.readthedocs.io/en/latest/tutorials/pyPPG_example.html

**Comment by NestorLiao** [comment]
Hello, Thank for you work firstly, Colab tutorial is fine until  I extract fiducials, it shows this error:

Traceback (most recent call last):
  File "/home/test/Desktop/GODA_pyPPG/colab.py", line 142, in <module>
    save_data(s, fp_new, bm, savingformat, savingfolder)
  File "/home/test/Desktop/GODA_pyPPG/pyPPG/datahandling.py", line 351, in save_data
    savingfolder = savingfolder.replace('/', '\\')
AttributeError: 'Fiducials' object has no attribute 'replace'


Do this related to windows?  I using linux to learn ppg, and thing to do for specific platform.
